-- MetaHunter_Wrath -- a LoadOnDemand sub-addon.
local MH = _G.MetaHunter
if not MH or not MH.Registry then
  error("MetaHunter_Wrath: MetaHunter (the main addon) isn't loaded -- check the Dependencies declaration in this addon's .toc")
end
local Registry = MH.Registry

local ROOTS = {
  {
    achievementID = 2136,
    title = "Glory of the Hero",
    category = "dungeon",
    guide = "Complete the Wrath of the Lich King heroic dungeon achievements listed by Blizzard.",
    criteria = {
      { achievementID = 1919, title = "On The Rocks" },
      { achievementID = 2036, title = "Intense Cold" },
      { achievementID = 1296, title = "Watch Him Die" },
      { achievementID = 1860, title = "Gotta Go!" },
      { achievementID = 2038, title = "Respect Your Elders" },
      { achievementID = 2151, title = "Consumption Junction" },
      { achievementID = 2057, title = "Oh Novos!" },
      { achievementID = 1865, title = "Lockdown!" },
      { achievementID = 2153, title = "A Void Dance" },
      { achievementID = 2040, title = "Less-rabi" },
      { achievementID = 1866, title = "Good Grief" },
      { achievementID = 2155, title = "Abuse the Ooze" },
      { achievementID = 1834, title = "Lightning Struck" },
      { achievementID = 1817, title = "The Culling of Time" },
      { achievementID = 2043, title = "The Incredible Hulk" },
      { achievementID = 2156, title = "My Girl Loves to Skadi All the Time" },
      { achievementID = 1871, title = "Experienced Drake Rider" },
      { achievementID = 2044, title = "Ruby Void" },
      { achievementID = 2046, title = "Amber Void" },
      { achievementID = 2150, title = "Split Personality" },
      { achievementID = 2037, title = "Chaos Theory" },
      { achievementID = 1297, title = "Hadronox Denied" },
      { achievementID = 1862, title = "Volazj's Quick Demise" },
      { achievementID = 2056, title = "Volunteer Work" },
      { achievementID = 2039, title = "Better Off Dred" },
      { achievementID = 1816, title = "Defenseless" },
      { achievementID = 2041, title = "Dehydration" },
      { achievementID = 1864, title = "What the Eck?" },
      { achievementID = 2058, title = "Snakes. Why'd It Have To Be Snakes?" },
      { achievementID = 2154, title = "Brann Spankin' New" },
      { achievementID = 1867, title = "Timely Death" },
      { achievementID = 2042, title = "Shatter Resistant" },
      { achievementID = 1872, title = "Zombiefest!" },
      { achievementID = 1873, title = "Lodi Dodi We Loves the Skadi" },
      { achievementID = 2157, title = "King's Bane" },
      { achievementID = 1868, title = "Make It Count" },
      { achievementID = 2045, title = "Emerald Void" },
    },
  },
  {
    achievementID = 2137,
    title = "Glory of the Raider (10 player)",
    category = "raid",
    guide = "Complete the original 10-player Wrath raid achievements listed by Blizzard.",
    criteria = {
      { achievementID = 578, title = "The Dedicated Few (10 player)" },
      { achievementID = 1856, title = "Make Quick Werk of Him (10 player)" },
      { achievementID = 1997, title = "Momma Said Knock You Out (10 player)" },
      { achievementID = 2180, title = "Subtraction (10 player)" },
      { achievementID = 1874, title = "You Don't Have an Eternity (10 player)" },
      { achievementID = 2047, title = "Gonna Go When the Volcano Blows (10 player)" },
      { achievementID = 2146, title = "The Hundred Club (10 player)" },
      { achievementID = 2148, title = "Denyin' the Scion (10 player)" },
      { achievementID = 1858, title = "Arachnophobia (10 player)" },
      { achievementID = 1996, title = "The Safety Dance (10 player)" },
      { achievementID = 2178, title = "Shocking! (10 player)" },
      { achievementID = 622, title = "The Spellweaver's Downfall (10 player)" },
      { achievementID = 1869, title = "A Poke in the Eye (10 player)" },
      { achievementID = 2051, title = "The Twilight Zone (10 player)" },
      { achievementID = 2176, title = "And They Would All Go Down Together (10 player)" },
      { achievementID = 2184, title = "Just Can't Get Enough (10 player)" },
    },
  },
  {
    achievementID = 2138,
    title = "Glory of the Raider (25 player)",
    category = "raid",
    guide = "Complete the original 25-player Wrath raid achievements listed by Blizzard.",
    criteria = {
      { achievementID = 579, title = "The Dedicated Few (25 player)" },
      { achievementID = 1857, title = "Make Quick Werk of Him (25 player)" },
      { achievementID = 2140, title = "Momma Said Knock You Out (25 player)" },
      { achievementID = 2177, title = "And They Would All Go Down Together (25 player)" },
      { achievementID = 623, title = "The Spellweaver's Downfall (25 player)" },
      { achievementID = 1870, title = "A Poke in the Eye (25 player)" },
      { achievementID = 2149, title = "Denyin' the Scion (25 player)" },
      { achievementID = 2147, title = "The Hundred Club (25 player)" },
      { achievementID = 1859, title = "Arachnophobia (25 player)" },
      { achievementID = 2139, title = "The Safety Dance (25 player)" },
      { achievementID = 2179, title = "Shocking! (25 player)" },
      { achievementID = 2181, title = "Subtraction (25 player)" },
      { achievementID = 1875, title = "You Don't Have an Eternity (25 player)" },
      { achievementID = 2048, title = "Gonna Go When the Volcano Blows (25 player)" },
      { achievementID = 2054, title = "The Twilight Zone (25 player)" },
      { achievementID = 2185, title = "Just Can't Get Enough (25 player)" },
    },
  },
  {
    achievementID = 12401,
    title = "Glory of the Ulduar Raider",
    category = "raid",
    guide = "Complete the current Retail Ulduar raid achievements listed by Blizzard.",
    criteria = {
      { achievementID = 12320, title = "Orbit-uary" },
      { achievementID = 12322, title = "Iron Dwarf, Medium Rare" },
      { achievementID = 12334, title = "I Choose You, Steelbreaker" },
      { achievementID = 12341, title = "Crazy Cat Lady" },
      { achievementID = 12352, title = "Lose Your Illusion" },
      { achievementID = 12369, title = "Firefighter" },
      { achievementID = 12387, title = "One Light in the Darkness" },
      { achievementID = 12325, title = "Stokin' the Furnace" },
      { achievementID = 12330, title = "Heartbreaker" },
      { achievementID = 12338, title = "Disarmed" },
      { achievementID = 12347, title = "I Could Say That This Cache Was Rare" },
      { achievementID = 12366, title = "Knock, Knock, Knock on Wood" },
      { achievementID = 12373, title = "I Love the Smell of Saronite in the Morning" },
    },
  },
  {
    achievementID = 4602,
    title = "Glory of the Icecrown Raider (10 player)",
    category = "raid",
    guide = "Complete the 10-player Icecrown Citadel raid achievements listed by Blizzard.",
    criteria = {
      { achievementID = 4628, title = "Heroic: Storming the Citadel (10 player)" },
      { achievementID = 4630, title = "Heroic: The Crimson Hall (10 player)" },
      { achievementID = 4534, title = "Boned (10 player)" },
      { achievementID = 4536, title = "I'm on a Boat (10 player)" },
      { achievementID = 4538, title = "Dances with Oozes (10 player)" },
      { achievementID = 4578, title = "Nausea, Heartburn, Indigestion... (10 player)" },
      { achievementID = 4539, title = "Once Bitten, Twice Shy (10 player)" },
      { achievementID = 4580, title = "All You Can Eat (10 player)" },
      { achievementID = 4629, title = "Heroic: The Plagueworks (10 player)" },
      { achievementID = 4631, title = "Heroic: The Frostwing Halls (10 player)" },
      { achievementID = 4535, title = "Full House (10 player)" },
      { achievementID = 4537, title = "I've Gone and Made a Mess (10 player)" },
      { achievementID = 4577, title = "Flu Shot Shortage (10 player)" },
      { achievementID = 4582, title = "The Orb Whisperer (10 player)" },
      { achievementID = 4579, title = "Portal Jockey (10 player)" },
      { achievementID = 4601, title = "Been Waiting a Long Time for This (10 player)" },
    },
  },
  {
    achievementID = 4603,
    title = "Glory of the Icecrown Raider (25 player)",
    category = "raid",
    guide = "Complete the 25-player Icecrown Citadel raid achievements listed by Blizzard.",
    criteria = {
      { achievementID = 4632, title = "Heroic: Storming the Citadel (25 player)" },
      { achievementID = 4634, title = "Heroic: The Crimson Hall (25 player)" },
      { achievementID = 4610, title = "Boned (25 player)" },
      { achievementID = 4612, title = "I'm on a Boat (25 player)" },
      { achievementID = 4614, title = "Dances with Oozes (25 player)" },
      { achievementID = 4616, title = "Nausea, Heartburn, Indigestion... (25 player)" },
      { achievementID = 4618, title = "Once Bitten, Twice Shy (25 player)" },
      { achievementID = 4620, title = "All You Can Eat (25 player)" },
      { achievementID = 4622, title = "Neck-Deep in Vile (25 player)" },
      { achievementID = 4633, title = "Heroic: The Plagueworks (25 player)" },
      { achievementID = 4635, title = "Heroic: The Frostwing Halls (25 player)" },
      { achievementID = 4611, title = "Full House (25 player)" },
      { achievementID = 4613, title = "I've Gone and Made a Mess (25 player)" },
      { achievementID = 4615, title = "Flu Shot Shortage (25 player)" },
      { achievementID = 4617, title = "The Orb Whisperer (25 player)" },
      { achievementID = 4619, title = "Portal Jockey (25 player)" },
      { achievementID = 4621, title = "Been Waiting a Long Time for This (25 player)" },
    },
  },
}

Registry:RegisterExpansion("wrath", ROOTS)
