-- MetaHunter_Cataclysm -- a LoadOnDemand sub-addon.
local MH = _G.MetaHunter
if not MH or not MH.Registry then
  error("MetaHunter_Cataclysm: MetaHunter (the main addon) isn't loaded -- check the Dependencies declaration in this addon's .toc")
end
local Registry = MH.Registry

local ROOTS = {
  {
    achievementID = 4845,
    title = "Glory of the Cataclysm Hero",
    category = "dungeon",
    guide = "Complete the Cataclysm dungeon achievements listed by Blizzard.",
    criteria = {
      {
        achievementID = 4844,
        title = "Cataclysm Dungeon Hero",
        criteria = {
          { achievementID = 5060, title = "Heroic: Blackrock Caverns" },
          { achievementID = 5061, title = "Heroic: Throne of the Tides" },
          { achievementID = 5062, title = "Heroic: Grim Batol" },
          { achievementID = 5063, title = "Heroic: The Stonecore" },
          { achievementID = 5064, title = "Heroic: The Vortex Pinnacle" },
          { achievementID = 5065, title = "Heroic: Halls of Origination" },
          { achievementID = 5066, title = "Heroic: Lost City of the Tol'vir" },
          { achievementID = 5083, title = "Heroic: Deadmines" },
          { achievementID = 5093, title = "Heroic: Shadowfang Keep" },
        },
      },
      { achievementID = 5282, title = "Arrested Development" },
      { achievementID = 5284, title = "Ascendant Descending" },
      { achievementID = 5288, title = "No Static at All" },
      { achievementID = 5290, title = "Kill It With Fire!" },
      { achievementID = 5292, title = "Headed South" },
      { achievementID = 5294, title = "Straw That Broke the Camel's Back" },
      { achievementID = 5296, title = "Faster Than the Speed of Light" },
      { achievementID = 5367, title = "Rat Pack" },
      { achievementID = 5369, title = "It's Frost Damage" },
      { achievementID = 5371, title = "Vigorous VanCleef Vindicator" },
      { achievementID = 5504, title = "To the Ground!" },
      { achievementID = 5298, title = "Don't Need to Break Eggs to Make an Omelet" },
      { achievementID = 5281, title = "Crushing Bones and Cracking Skulls" },
      { achievementID = 5283, title = "Too Hot to Handle" },
      { achievementID = 5287, title = "Rotten to the Core" },
      { achievementID = 5289, title = "Extra Credit Bonus Stage" },
      { achievementID = 5291, title = "Acrocalypse Now" },
      { achievementID = 5293, title = "I Hate That Song" },
      { achievementID = 5295, title = "Sun of a...." },
      { achievementID = 5366, title = "Ready for Raiding" },
      { achievementID = 5368, title = "Prototype Prodigy" },
      { achievementID = 5370, title = "I'm on a Diet" },
      { achievementID = 5503, title = "Pardon Denied" },
      { achievementID = 5505, title = "Bullet Time" },
    },
  },
  {
    achievementID = 4853,
    title = "Glory of the Cataclysm Raider",
    category = "raid",
    guide = "Complete the tier 11 Cataclysm raid achievements listed by Blizzard.",
    criteria = {
      { achievementID = 5094, title = "Heroic: Magmaw" },
      { achievementID = 5108, title = "Heroic: Maloriak" },
      { achievementID = 5115, title = "Heroic: Chimaeron" },
      { achievementID = 5118, title = "Heroic: Halfus Wyrmbreaker" },
      { achievementID = 5119, title = "Heroic: Ascendant Council" },
      { achievementID = 5122, title = "Heroic: Conclave of Wind" },
      { achievementID = 5306, title = "Parasite Evening" },
      { achievementID = 5308, title = "Silence is Golden" },
      { achievementID = 5310, title = "Aberrant Behavior" },
      { achievementID = 5300, title = "The Only Escape" },
      { achievementID = 5311, title = "Elementary" },
      { achievementID = 5304, title = "Stay Chill" },
      { achievementID = 5107, title = "Heroic: Omnotron Defense System" },
      { achievementID = 5109, title = "Heroic: Atramedes" },
      { achievementID = 5116, title = "Heroic: Nefarian" },
      { achievementID = 5117, title = "Heroic: Valiona and Theralion" },
      { achievementID = 5120, title = "Heroic: Cho'gall" },
      { achievementID = 5123, title = "Heroic: Al'Akir" },
      { achievementID = 5307, title = "Achieve-a-tron" },
      { achievementID = 5309, title = "Full of Sound and Fury" },
      { achievementID = 4849, title = "Keeping it in the Family" },
      { achievementID = 4852, title = "Double Dragon" },
      { achievementID = 5312, title = "The Abyss Will Gaze Back Into You" },
      { achievementID = 5305, title = "Four Play" },
    },
  },
  {
    achievementID = 5828,
    title = "Glory of the Firelands Raider",
    category = "raid",
    guide = "Complete the Firelands raid achievements listed by Blizzard.",
    criteria = {
      { achievementID = 5807, title = "Heroic: Beth'tilac" },
      { achievementID = 5806, title = "Heroic: Shannox" },
      { achievementID = 5805, title = "Heroic: Baleroc" },
      { achievementID = 5821, title = "Death from Above" },
      { achievementID = 5813, title = "Do a Barrel Roll!" },
      { achievementID = 5830, title = "Share the Pain" },
      { achievementID = 5808, title = "Heroic: Lord Rhyolith" },
      { achievementID = 5809, title = "Heroic: Alysrazor" },
      { achievementID = 5804, title = "Heroic: Majordomo Fandral Staghelm" },
      { achievementID = 5810, title = "Not an Ambi-Turner" },
      { achievementID = 5829, title = "Bucket List" },
      { achievementID = 5799, title = "Only the Penitent..." },
    },
  },
  {
    achievementID = 6169,
    title = "Glory of the Dragon Soul Raider",
    category = "raid",
    guide = "Complete the Dragon Soul raid achievements listed by Blizzard.",
    criteria = {
      { achievementID = 6109, title = "Heroic: Morchok" },
      { achievementID = 6111, title = "Heroic: Yor'sahj the Unsleeping" },
      { achievementID = 6113, title = "Heroic: Ultraxion" },
      { achievementID = 6174, title = "Don't Stand So Close to Me" },
      { achievementID = 6128, title = "Ping Pong Champion" },
      { achievementID = 6105, title = "Deck Defender" },
      { achievementID = 6180, title = "Chromatic Champion" },
      { achievementID = 6110, title = "Heroic: Warlord Zon'ozz" },
      { achievementID = 6112, title = "Heroic: Hagara the Stormbinder" },
      { achievementID = 6114, title = "Heroic: Warmaster Blackhorn" },
      { achievementID = 6129, title = "Taste the Rainbow!" },
      { achievementID = 6084, title = "Minutes to Midnight" },
      { achievementID = 6133, title = "Maybe He'll Get Dizzy..." },
    },
  },
}

Registry:RegisterExpansion("cataclysm", ROOTS)
