-- MetaHunter_MistsOfPandaria -- a LoadOnDemand sub-addon.
local MH = _G.MetaHunter
if not MH or not MH.Registry then
  error("MetaHunter_MistsOfPandaria: MetaHunter (the main addon) isn't loaded -- check the Dependencies declaration in this addon's .toc")
end
local Registry = MH.Registry

local ROOTS = {
  {
    achievementID = 6927,
    title = "Glory of the Pandaria Hero",
    category = "dungeon",
    guide = "Complete the Mists of Pandaria dungeon achievements listed by Blizzard.",
    criteria = {
      {
        achievementID = 6925,
        title = "Pandaria Dungeon Hero",
        criteria = {
          { achievementID = 6758, title = "Heroic: Temple of the Jade Serpent" },
          { achievementID = 6456, title = "Heroic: Stormstout Brewery" },
          { achievementID = 6756, title = "Heroic: Mogu'shan Palace" },
          { achievementID = 6763, title = "Heroic: Siege of Niuzao Temple" },
          { achievementID = 6470, title = "Heroic: Shado-Pan Monastery" },
          { achievementID = 6759, title = "Heroic: Gate of the Setting Sun" },
          { achievementID = 6760, title = "Heroic: Scarlet Halls" },
          { achievementID = 6761, title = "Heroic: Scarlet Monastery" },
          { achievementID = 6762, title = "Heroic: Scholomance" },
        },
      },
      { achievementID = 6475, title = "Cleaning Up" },
      { achievementID = 6420, title = "Hopocalypse Now!" },
      { achievementID = 6400, title = "How Did He Get Up There?" },
      { achievementID = 6478, title = "Glintrok N' Roll" },
      { achievementID = 6713, title = "Quarrelsome Quilen Quintet" },
      { achievementID = 6472, title = "The Obvious Solution" },
      { achievementID = 6479, title = "Bomberman" },
      { achievementID = 6684, title = "Humane Society" },
      { achievementID = 6928, title = "Burning Man" },
      { achievementID = 6531, title = "Attention to Detail" },
      { achievementID = 6396, title = "Sanguinarian" },
      { achievementID = 6688, title = "Where's My Air Support?" },
      { achievementID = 6822, title = "Run with the Wind" },
      { achievementID = 6460, title = "Hydrophobia" },
      { achievementID = 6671, title = "Seeds of Doubt" },
      { achievementID = 6089, title = "Keep Rollin' Rollin' Rollin'" },
      { achievementID = 6402, title = "Ling-Ting's Herbal Journey" },
      { achievementID = 6736, title = "What Does This Button Do?" },
      { achievementID = 6477, title = "Respect" },
      { achievementID = 6471, title = "Hate Leads to Suffering" },
      { achievementID = 6476, title = "Conscriptinator" },
      { achievementID = 6427, title = "Mosh Pit" },
      { achievementID = 6929, title = "And Stay Dead!" },
      { achievementID = 6394, title = "Rattle No More" },
      { achievementID = 6821, title = "School's Out Forever" },
      { achievementID = 6485, title = "Return to Sender" },
      { achievementID = 6715, title = "Polyformic Acid Science" },
    },
  },
  {
    achievementID = 6932,
    title = "Glory of the Pandaria Raider",
    category = "raid",
    guide = "Complete the Mogu'shan Vaults, Heart of Fear, and Terrace of Endless Spring raid achievements listed by Blizzard.",
    criteria = {
      { achievementID = 6823, title = "Must Love Dogs" },
      { achievementID = 7056, title = "Sorry, Were You Looking for This?" },
      { achievementID = 6937, title = "Overzealous" },
      { achievementID = 6553, title = "Like an Arrow to the Face" },
      { achievementID = 6518, title = "I Heard You Like Amber..." },
      { achievementID = 6717, title = "Power Overwhelming" },
      { achievementID = 6933, title = "Who's Got Two Green Thumbs?" },
      { achievementID = 6719, title = "Heroic: Stone Guard" },
      { achievementID = 6721, title = "Heroic: Gara'jal the Spiritbinder" },
      { achievementID = 6723, title = "Heroic: Elegon" },
      { achievementID = 6725, title = "Heroic: Imperial Vizier Zor'lok" },
      { achievementID = 6727, title = "Heroic: Garalon" },
      { achievementID = 6729, title = "Heroic: Amber-Shaper Un'sok" },
      { achievementID = 6731, title = "Heroic: Protectors of the Endless" },
      { achievementID = 6733, title = "Heroic: Lei Shi" },
      { achievementID = 6674, title = "Anything You Can Do, I Can Do Better..." },
      { achievementID = 6686, title = "Straight Six" },
      { achievementID = 6936, title = "Candle in the Wind" },
      { achievementID = 6683, title = "Less Than Three" },
      { achievementID = 6922, title = "Timing is Everything" },
      { achievementID = 6824, title = "Face Clutchers" },
      { achievementID = 6825, title = "The Mind-Killer" },
      { achievementID = 6720, title = "Heroic: Feng the Accursed" },
      { achievementID = 6722, title = "Heroic: Four Kings" },
      { achievementID = 6724, title = "Heroic: Will of the Emperor" },
      { achievementID = 6726, title = "Heroic: Blade Lord Ta'yak" },
      { achievementID = 6728, title = "Heroic: Wind Lord Mel'jarak" },
      { achievementID = 6730, title = "Heroic: Grand Empress Shek'zeer" },
      { achievementID = 6732, title = "Heroic: Tsulong" },
    },
  },
  {
    achievementID = 8124,
    title = "Glory of the Thundering Raider",
    category = "raid",
    guide = "Complete the Throne of Thunder raid achievements listed by Blizzard.",
    criteria = {
      { achievementID = 8056, title = "Heroic: Jin'rokh the Breaker" },
      { achievementID = 8058, title = "Heroic: Council of Elders" },
      { achievementID = 8060, title = "Heroic: Megaera" },
      { achievementID = 8062, title = "Heroic: Durumu the Forgotten" },
      { achievementID = 8064, title = "Heroic: Dark Animus" },
      { achievementID = 8066, title = "Heroic: Twin Empyreans" },
      { achievementID = 8038, title = "Cretaceous Collector" },
      { achievementID = 8077, title = "One-Up" },
      { achievementID = 8097, title = "Soft Hands" },
      { achievementID = 8037, title = "Genetically Unmodified Organism" },
      { achievementID = 8087, title = "Can't Touch This" },
      { achievementID = 8090, title = "A Complete Circuit" },
      { achievementID = 8057, title = "Heroic: Horridon" },
      { achievementID = 8059, title = "Heroic: Tortos" },
      { achievementID = 8061, title = "Heroic: Ji-Kun" },
      { achievementID = 8063, title = "Heroic: Primordius" },
      { achievementID = 8065, title = "Heroic: Iron Qon" },
      { achievementID = 8094, title = "Lightning Overload" },
      { achievementID = 8073, title = "Cage Match" },
      { achievementID = 8082, title = "Head Case" },
      { achievementID = 8098, title = "You Said Crossing the Streams Was Bad" },
      { achievementID = 8081, title = "Ritualist Who?" },
      { achievementID = 8086, title = "From Dusk 'til Dawn" },
    },
  },
  {
    achievementID = 8454,
    title = "Glory of the Orgrimmar Raider",
    category = "raid",
    guide = "Complete the Siege of Orgrimmar raid achievements listed by Blizzard.",
    criteria = {
      { achievementID = 8536, title = "No More Tears" },
      { achievementID = 8532, title = "None Shall Pass" },
      { achievementID = 8530, title = "The Immortal Vanguard" },
      { achievementID = 8453, title = "Rescue Raiders" },
      { achievementID = 8538, title = "Unlimited Potential" },
      { achievementID = 8527, title = "Giant Dinosaur vs. Mega Snail" },
      { achievementID = 8531, title = "Now We are the Paragon" },
      { achievementID = 8528, title = "Go Long" },
      { achievementID = 8521, title = "Swallow Your Pride" },
      { achievementID = 8520, title = "Fire in the Hole!" },
      { achievementID = 8448, title = "Gamon Will Save Us!" },
      { achievementID = 8529, title = "Criss Cross" },
      { achievementID = 8543, title = "Lasers and Magnets and Drills! Oh My!" },
      { achievementID = 8537, title = "Strike!" },
    },
  },
}

Registry:RegisterExpansion("mists-of-pandaria", ROOTS)
